### ISSUE TITLE
Error SQL:PRAGMA foreign_keys = ON

### ISSUE THREAD

**Issue by ahadimuhsin** [LaravelDaily/Test-Laravel-File-Upload#9]
Hi,
I was encounter while running the test.
It said "could not find driver (SQL: PRAGMA foreign_keys = ON;)";
This specific error for using SQLite. But I am using MySQL.

How to solve this?
Thanks

**Comment by PovilasKorop** [comment]
@ahadimuhsin sorry I haven't run this on MySQL so I don't know. The test is configured to run on SQLite in phpunit.xml

**Comment by ahadimuhsin** [comment]
Fixed now. Set foreign_key_constraints to false in sqlite array in database.php
